# Generated by Django 5.1.5 on 2025-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
